wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8182:80

wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: test

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: test

